"""mensagem descritiva

Revision ID: 673ec1d0c630
Revises: 
Create Date: 2025-08-12 20:27:30.976161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673ec1d0c630'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ataque', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('defesa', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('at_esp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('de_esp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('velocidade', sa.Integer(), nullable=False))
        batch_op.alter_column('typesec',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('typesec',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('velocidade')
        batch_op.drop_column('de_esp')
        batch_op.drop_column('at_esp')
        batch_op.drop_column('defesa')
        batch_op.drop_column('ataque')
        batch_op.drop_column('hp')

    # ### end Alembic commands ###
